### ISSUE TITLE
Bug: "Cannot find the project associated with this Pipenv environment"

### ISSUE THREAD

**Issue by tobiashochguertel** [tonybaloney/pycharm-security#179]
**Describe the bug**

```
The following command was executed:

Pipenv 

The exit code: -1
The error output of the command:



Cannot find the project associated with this Pipenv environment
	at com.jetbrains.python.sdk.pipenv.PipenvKt.runPipEnv(pipenv.kt:197)
	at com.jetbrains.python.packaging.pipenv.PyPipEnvPackageManager.refreshAndGetPackages(PyPipEnvPackageManager.kt:91)
	at security.packaging.PyPackageSecurityScan.checkPackagesInSdks(PyPackageSecurityScan.kt:46)
	at security.packaging.PyPackageSecurityScan.checkPackages(PyPackageSecurityScan.kt:30)
	at security.packaging.PythonPackageVulnerabilityStartupTask$runActivity$1.run(PythonPackageVulnerabilityStartupTask.kt:16)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
Install the Plugin, start the IDE, open a project which use `pipenv`

**Screenshots**

![image](https://user-images.githubusercontent.com/3332669/102690598-cc508c80-4206-11eb-803f-50a9c9974ecd.png)

![image](https://user-images.githubusercontent.com/3332669/102690630-fbff9480-4206-11eb-9448-e39ff3cc81a7.png)

**Additional context**
 - Plugin Version: `Python Security, v.1.22.2`
 - PyCharm Version (or IDE version): `PyCharm Professional 2020.3, PY-203.5981.165, built on December 19, 2020`
 - Python Version: `3.9.0 (Mac OS, Big Sur)`

**Comment by KukumavMozolo** [comment]
same problem
