### ISSUE TITLE
NullPointerException after plugin upgrade to v1.23.0

### ISSUE THREAD

**Issue by subuserzero** [tonybaloney/pycharm-security#184]
**Describe the bug**
java.lang.NullPointerException encountered after upgrading PyCharm plugin to v1.23.0.

**To Reproduce**
Code or Steps to reproduce the behavior:
1. Have previously installed older version of PS plugin (I presume the most recent prior version, but can't be 100% sure)
1. In PyCharm UI, accept prompt to upgrade plugin in notification balloon
2. Restart PyCharm
3. Open IDE fatal error dialogue box
4. See error (noted below)

**Expected behavior**
Expected plugin to upgrade w/out NPE

**Screenshots**
`
java.lang.NullPointerException: this.javaClass.classLoad…y-db/insecure_full.json") must not be null
	at security.packaging.SafetyDbChecker.<init>(SafetyDbChecker.kt:35)
	at security.packaging.PyPackageSecurityScan.checkPackages(PyPackageSecurityScan.kt:30)
	at security.packaging.PythonPackageVulnerabilityStartupTask$runActivity$1.run(PythonPackageVulnerabilityStartupTask.kt:16)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
`
**Additional context**
 - Plugin Version: 1.23.0
 - PyCharm Version (or IDE version): PyCharm 2020.3.1 (Professional Edition)
 - Build #PY-203.6682.86, built on December 23, 2020
 - Runtime version: 11.0.9.1+11-b1145.37 x86_64
 - VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
 - macOS 10.14.6
 - GC: ParNew, ConcurrentMarkSweep
 - Memory: 1981M
 - Cores: 8
 - Python Version: 3.7

**Comment by sandguardian** [comment]
Same for me. How can I revert to previous version?

**Comment by tonybaloney** [comment]
Oh no! Sorry about that. I've requested it to be removed from the Jetbrains store. You can revert back to a previous version in the plugin manager

**Comment by tonybaloney** [comment]
Just shipped a fixed version. It should be out on the jetbrains marketplace.

I'd somehow removed the SafetyDB files from the package before publishing it.

**Comment by subuserzero** [comment]
Confirmed no NPE encountered upgrading to v1.23.1. Thanks for the quick fix!
